sudo: required
language: generic
  
services:
  - docker

before_install:
  - docker build -t deeptiranjanpalo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true deeptiranjanpalo/docker-react npm run test -- --coverage
